# Generated by Django 5.2.1 on 2025-07-17 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(upload_to='avatars/gif/', verbose_name='GIF-анимация')),
            ],
            options={
                'verbose_name': 'Анимация аватара',
                'verbose_name_plural': 'Анимации аватаров',
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя аватара')),
                ('description', models.TextField(verbose_name='Описание аватара')),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название стадии')),
                ('description', models.TextField(verbose_name='Описание стадии')),
                ('required_spending', models.PositiveIntegerField(default=0, verbose_name='Требуемая сумма трат')),
            ],
            options={
                'verbose_name': 'Стадия',
                'verbose_name_plural': 'Стадии',
                'ordering': ['required_spending'],
            },
        ),
        migrations.CreateModel(
            name='AvatarStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_img', models.ImageField(upload_to='avatars/photos/', verbose_name='Изображение')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_stages', to='avatar_app.avatar', verbose_name='Аватар')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_stages', to='avatar_app.stage', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Стадия конкретного аватара',
                'verbose_name_plural': 'Стадии конкретных аватаров',
                'unique_together': {('avatar', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='AvatarOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit', models.ImageField(upload_to='avatars/clothes/previews/', verbose_name='Картинка комплекта (только одежда)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (в баллах)')),
                ('custom_img', models.ImageField(upload_to='avatars/clothes/avatar_images/', verbose_name='Картинка аватара в этой одежде')),
                ('custom_animations', models.ManyToManyField(blank=True, to='avatar_app.animation', verbose_name='Анимации аватара в одежде')),
                ('avatar_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='avatar_app.avatarstage', verbose_name='Стадия аватара')),
            ],
            options={
                'verbose_name': 'Одежда для аватара',
                'verbose_name_plural': 'Одежда для аватаров',
            },
        ),
        migrations.AddField(
            model_name='animation',
            name='avatar_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='avatar_app.avatarstage', verbose_name='Стадия аватара'),
        ),
        migrations.CreateModel(
            name='UserAvatarProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spending', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, verbose_name='Текущий выбранный аватар')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_progress', to='avatar_app.avatar', verbose_name='Аватар')),
                ('current_outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatar_app.avataroutfit', verbose_name='Надетая одежда')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_progress', to='avatar_app.stage', verbose_name='Стадия аватара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогрессы пользователей',
                'unique_together': {('user', 'avatar')},
            },
        ),
    ]
