# Generated by Django 5.2.1 on 2025-07-17 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatarprogress',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_progress', to='avatar_app.avatar', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='useravatarprogress',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_progress', to='avatar_app.stage', verbose_name='Стадия аватара'),
        ),
        migrations.AlterField(
            model_name='useravatarprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='useravatarprogress',
            unique_together={('user', 'avatar')},
        ),
    ]
