# Generated by Django 5.2.1 on 2025-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_app', '0002_alter_useravatarprogress_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='required_spending',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Требуемая сумма трат'),
        ),
    ]
