# Generated by Django 5.2.1 on 2025-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_app', '0002_outfitpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avataroutfit',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена (в бонусах)'),
        ),
    ]
