# Generated by Django 5.2.1 on 2025-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_app', '0003_alter_stage_required_spending'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatarprogress',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Текущий выбранный аватар'),
        ),
    ]
