# Generated by Django 5.2.1 on 2025-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_mailing_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='from_user',
        ),
        migrations.AddField(
            model_name='mailing',
            name='tg_user_id',
            field=models.BigIntegerField(default=0, verbose_name='ID пользователя Telegram'),
            preserve_default=False,
        ),
    ]
