# Generated by Django 5.2.1 on 2025-06-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование расслыки'),
        ),
    ]
