# Generated by Django 5.2.1 on 2025-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0006_alter_subscription_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
