# Generated by Django 5.2.1 on 2025-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название мероприятия')),
                ('description', models.TextField(max_length=255, verbose_name='Описание мероприятия')),
                ('info', models.TextField(verbose_name='Дополнительная информация')),
                ('start_date', models.DateTimeField(verbose_name='Начало мероприятия')),
                ('end_date', models.DateTimeField(verbose_name='Окончание мероприятия')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('photo', models.CharField(max_length=255, verbose_name='Фото мероприятия')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на регистрацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
