# Generated by Django 5.2.1 on 2025-07-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='events/photos/', verbose_name='Фото мероприятия'),
        ),
    ]
