# Generated by Django 5.2.1 on 2025-07-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название мероприятия'),
        ),
    ]
