# Generated by Django 5.2.1 on 2025-07-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='enable_registration',
            field=models.BooleanField(default=False, verbose_name='Доступна регистрация'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_tickets',
            field=models.BooleanField(default=False, verbose_name='Доступна покупка билетов'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на регистрацию'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылку на покупку билета'),
        ),
    ]
