# Generated by Django 5.2.1 on 2025-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на регистрацию'),
        ),
    ]
