# Generated by Django 5.2.1 on 2025-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_event_description_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(max_length=400, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, max_length=70, null=True, verbose_name='Ссылка на регистрацию'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, max_length=70, null=True, verbose_name='Ссылка на покупку билета'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
