# Generated by Django 5.2.1 on 2025-08-24 10:04

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_event_info_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='events/photos/', verbose_name='Фото'),
        ),
    ]
