# Generated by Django 5.2.1 on 2025-10-08 14:53

import dzavod.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_event_info_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='events/photos/', validators=[dzavod.validators.validate_image], verbose_name='Фото'),
        ),
    ]
