# Generated by Django 5.2.1 on 2025-07-21 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='route_app.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
                'unique_together': {('number', 'building')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('location_type', models.CharField(choices=[('office', 'Офис'), ('hall', 'Зал'), ('corridor', 'Коридор'), ('elevator', 'Лифт'), ('stairs', 'Лестница'), ('entry', 'Вход'), ('other', 'Другое')], max_length=20, verbose_name='Тип локации')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='route_app.floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_end', to='route_app.location', verbose_name='Конечная локация')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_start', to='route_app.location', verbose_name='Начальная локация')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidirectional', models.BooleanField(default=True, verbose_name='Двунаправленная связь')),
                ('cost', models.FloatField(default=1.0, help_text='Стоимость перехода: метры, секунды и т.п.', verbose_name='Стоимость перехода')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='route_app.location', verbose_name='Откуда')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='route_app.location', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
                'unique_together': {('from_location', 'to_location')},
            },
        ),
        migrations.CreateModel(
            name='LocationCorner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Координата X угла')),
                ('y', models.FloatField(help_text='Координата Y угла')),
                ('order', models.PositiveSmallIntegerField(help_text='Порядок обхода углов (по часовой стрелке)', verbose_name='Порядок обхода углов')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corners', to='route_app.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Угол',
                'verbose_name_plural': 'Углы',
                'ordering': ['order'],
                'unique_together': {('location', 'order')},
            },
        ),
    ]
