# Generated by Django 5.2.1 on 2025-07-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='route_app.building')),
            ],
            options={
                'unique_together': {('number', 'building')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('office', 'Офис'), ('hall', 'Зал'), ('corridor', 'Коридор'), ('elevator', 'Лифт'), ('stairs', 'Лестница'), ('entry', 'Вход'), ('other', 'Другое')], max_length=20)),
                ('x', models.FloatField(help_text='Координата X на плане')),
                ('y', models.FloatField(help_text='Координата Y на плане')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='route_app.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_end', to='route_app.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_start', to='route_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidirectional', models.BooleanField(default=True)),
                ('cost', models.FloatField(default=1.0, help_text='Стоимость перехода: метры, секунды и т.п.')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='route_app.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='route_app.location')),
            ],
            options={
                'unique_together': {('from_location', 'to_location')},
            },
        ),
    ]
