# Generated by Django 5.2.1 on 2025-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_app', '0002_locationtype_alter_location_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtype',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
