# Generated by Django 5.2.1 on 2025-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_app', '0003_locationtype_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtype',
            name='code',
        ),
        migrations.AddField(
            model_name='locationtype',
            name='color',
            field=models.CharField(default='#dddddd', help_text='Например, #ff0000 для красного', max_length=7, verbose_name='Цвет (hex)'),
        ),
    ]
