# Generated by Django 5.2.1 on 2025-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_app', '0004_remove_locationtype_code_locationtype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='cost',
            field=models.FloatField(default=1.0, help_text='Стоимость перехода, м', verbose_name='Стоимость перехода, м'),
        ),
    ]
