# Generated by Django 5.2.1 on 2025-08-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0002_alter_resident_max_deduct_percent_and_more'),
        ('route_app', '0005_alter_connection_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='tours/images/', verbose_name='Фото')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('residents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='resident_app.resident', verbose_name='Резидент')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
