# Generated by Django 5.2.1 on 2025-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0004_category_parent'),
        ('route_app', '0007_alter_tour_description_alter_tour_full_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='residents',
        ),
        migrations.AddField(
            model_name='tour',
            name='residents',
            field=models.ManyToManyField(related_name='tours', to='resident_app.resident', verbose_name='Резиденты'),
        ),
    ]
