# Generated by Django 5.2.1 on 2025-10-08 14:53

import dzavod.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_app', '0008_remove_tour_residents_tour_residents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/images/', validators=[dzavod.validators.validate_image], verbose_name='Фото'),
        ),
    ]
