# Generated by Django 5.2.1 on 2025-06-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_birth_date_user_email_user_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона'),
        ),
    ]
