# Generated by Django 5.2.1 on 2025-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('design_admin', 'Админ завода'), ('resident', 'Резидент'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
