# Generated by Django 5.2.1 on 2025-07-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления'),
        ),
    ]
