# Generated by Django 5.2.1 on 2025-07-18 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_user_enable_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_points', models.PositiveIntegerField(default=0, verbose_name='Баллы для приглашающего')),
                ('invitee_points', models.PositiveIntegerField(default=0, verbose_name='Баллы для приглашаемого')),
            ],
            options={
                'verbose_name': 'Настройки реферальных баллов',
                'verbose_name_plural': 'Настройки реферальных баллов',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True, verbose_name='Реферальный код')),
                ('is_rewarded', models.BooleanField(default=False, verbose_name='Награда начислена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('invitee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_used', to=settings.AUTH_USER_MODEL, verbose_name='Кого пригласили')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL, verbose_name='Приглашающий')),
            ],
            options={
                'verbose_name': 'Реферальная ссылка',
                'verbose_name_plural': 'Реферальные ссылки',
                'unique_together': {('inviter', 'invitee')},
            },
        ),
    ]
