# Generated by Django 5.2.1 on 2025-07-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_referralsettings_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Реферальный код'),
        ),
    ]
