# Generated by Django 5.2.1 on 2025-07-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Использованный реферальный код'),
        ),
    ]
