# Generated by Django 5.2.1 on 2025-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_referral_referral_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Использованный реферальный код'),
        ),
    ]
