# Generated by Django 5.2.1 on 2025-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_user_referral_code_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralsettings',
            options={'verbose_name': 'Настройки реферальных бонусов', 'verbose_name_plural': 'Настройки реферальных бонусов'},
        ),
        migrations.AlterField(
            model_name='referralsettings',
            name='invitee_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусы для приглашаемого'),
        ),
        migrations.AlterField(
            model_name='referralsettings',
            name='inviter_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусы для приглашающего'),
        ),
    ]
