# Generated by Django 5.2.1 on 2025-07-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('working_time', models.TextField(blank=True, null=True, verbose_name='График работы')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер телефона')),
                ('official_website', models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Официальный сайт')),
                ('address', models.CharField(default='ул. Большая Новодмитровская, д. 36', max_length=255, verbose_name='Адрес')),
                ('building', models.CharField(max_length=20, verbose_name='Строение')),
                ('entrance', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вход')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('office', models.IntegerField(unique=True, verbose_name='Офис/Помещение')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='residents/photos/', verbose_name='Фото')),
                ('pin_code', models.CharField(max_length=6, unique=True, verbose_name='Пин-код')),
                ('points_per_100_rubles', models.PositiveIntegerField(verbose_name='Кол-во баллов за 100 р.')),
                ('max_deduct_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Максимальный процент от суммы покупки, который можно списать')),
                ('categories', models.ManyToManyField(related_name='residents', to='resident_app.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Резидент',
                'verbose_name_plural': 'Резиденты',
            },
        ),
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='Координата X')),
                ('y', models.FloatField(verbose_name='Координата Y')),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_marker', to='resident_app.resident', verbose_name='Резидент')),
            ],
            options={
                'verbose_name': 'Метка на карте',
                'verbose_name_plural': 'Метки на карте',
            },
        ),
    ]
