# Generated by Django 5.2.1 on 2025-07-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('info', models.TextField(verbose_name='Дополнительная информация')),
                ('working_time', models.TextField(blank=True, null=True, verbose_name='График работы')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер телефона')),
                ('official_website', models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Официальный сайт')),
                ('full_address', models.CharField(max_length=255, verbose_name='Полный адрес на территории завода')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('office', models.IntegerField(unique=True, verbose_name='Офис/Помещение')),
                ('photo', models.CharField(max_length=255, unique=True, verbose_name='Фото')),
                ('categories', models.ManyToManyField(related_name='residents', to='resident_app.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резидент',
                'verbose_name_plural': 'Резиденты',
            },
        ),
    ]
