# Generated by Django 5.2.1 on 2025-06-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('working_time', models.TextField(verbose_name='График работы')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер телефона')),
                ('official_website', models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Официальный сайт')),
                ('full_address', models.CharField(max_length=255, verbose_name='Полный адрес на территории завода')),
                ('floor', models.IntegerField(default=0, verbose_name='Этаж')),
                ('office', models.IntegerField(unique=True, verbose_name='Офис/Помещение')),
                ('category', models.CharField(choices=[('services', 'Услуги и развлечения'), ('retail', 'Ритейл'), ('gastro', 'Гастро')], max_length=32, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Резидент',
                'verbose_name_plural': 'Резиденты',
            },
        ),
    ]
