# Generated by Django 5.2.1 on 2025-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Пин-код'),
        ),
    ]
