# Generated by Django 5.2.1 on 2025-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории')),
                ('description', models.TextField(null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveField(
            model_name='resident',
            name='category',
        ),
        migrations.AddField(
            model_name='resident',
            name='categories',
            field=models.ManyToManyField(related_name='residents', to='resident_app.category'),
        ),
    ]
