# Generated by Django 5.2.1 on 2025-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='max_deduct_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Максимальный процент списания от суммы покупки'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='points_per_100_rubles',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во баллов за 100 р.'),
        ),
    ]
