# Generated by Django 5.2.1 on 2025-06-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='working_time',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
    ]
