# Generated by Django 5.2.1 on 2025-07-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0002_alter_resident_max_deduct_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='max_deduct_percent',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='points_per_100_rubles',
        ),
    ]
