# Generated by Django 5.2.1 on 2025-06-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0002_category_remove_resident_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='categories',
            new_name='category',
        ),
    ]
