# Generated by Django 5.2.1 on 2025-07-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0002_resident_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='pin_code',
            field=models.CharField(default=1, max_length=6, unique=True, verbose_name='Пин-код'),
            preserve_default=False,
        ),
    ]
