# Generated by Django 5.2.1 on 2025-06-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0003_rename_categories_resident_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='category',
            field=models.ManyToManyField(related_name='residents', to='resident_app.category', verbose_name='Категория'),
        ),
    ]
