# Generated by Django 5.2.1 on 2025-08-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0003_remove_resident_max_deduct_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resident_app.category', verbose_name='Родитель подкатегории'),
        ),
    ]
