# Generated by Django 5.2.1 on 2025-07-07 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0003_alter_resident_pin_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='categories',
            field=models.ManyToManyField(related_name='residents', to='resident_app.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
