# Generated by Django 5.2.1 on 2025-08-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0004_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='building',
            field=models.CharField(max_length=10, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='floor',
            field=models.IntegerField(max_length=10, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='office',
            field=models.IntegerField(max_length=10, verbose_name='Офис/Помещение'),
        ),
    ]
