# Generated by Django 5.2.1 on 2025-07-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0004_alter_resident_categories_alter_resident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='photo',
            field=models.ImageField(upload_to='residents/photos/', verbose_name='Фото'),
        ),
    ]
