# Generated by Django 5.2.1 on 2025-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0005_alter_resident_building_alter_resident_entrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='floor',
            field=models.CharField(max_length=10, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='office',
            field=models.CharField(max_length=10, verbose_name='Офис/Помещение'),
        ),
    ]
