# Generated by Django 5.2.1 on 2025-06-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0005_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полный адрес на территории завода'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='office',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Офис/Помещение'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='working_time',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
    ]
