# Generated by Django 5.2.1 on 2025-10-08 14:53

import dzavod.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0006_alter_resident_floor_alter_resident_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/photos/', validators=[dzavod.validators.validate_image], verbose_name='Фото'),
        ),
    ]
