# Generated by Django 5.2.1 on 2025-06-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0006_alter_resident_floor_alter_resident_full_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='category',
            new_name='categories',
        ),
    ]
