# Generated by Django 5.2.1 on 2025-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0006_alter_resident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
