# Generated by Django 5.2.1 on 2025-06-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0007_rename_category_resident_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='categories',
            field=models.ManyToManyField(related_name='residents', to='resident_app.category', verbose_name='Категории'),
        ),
    ]
