# Generated by Django 5.2.1 on 2025-07-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0007_alter_resident_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='user',
        ),
    ]
