# Generated by Django 5.2.1 on 2025-07-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0008_remove_resident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/photos/', verbose_name='Фото'),
        ),
    ]
