# Generated by Django 5.2.1 on 2025-07-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0009_alter_resident_description_alter_resident_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='Координата X')),
                ('y', models.FloatField(verbose_name='Координата Y')),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_marker', to='resident_app.resident', verbose_name='Резидент')),
            ],
            options={
                'verbose_name': 'Метка на карте',
                'verbose_name_plural': 'Метки на карте',
            },
        ),
    ]
