# Generated by Django 5.2.1 on 2025-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0010_mapmarker'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.CharField(default='ул. Большая Новодмитровская, д. 36', max_length=255, verbose_name='Адрес'),
        ),
    ]
