# Generated by Django 5.2.1 on 2025-07-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0011_resident_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='full_address',
        ),
    ]
