# Generated by Django 5.2.1 on 2025-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0012_remove_resident_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='building',
            field=models.CharField(default='указать', max_length=20, verbose_name='Строение'),
        ),
        migrations.AddField(
            model_name='resident',
            name='entrance',
            field=models.CharField(default='указать', max_length=50, verbose_name='Вход'),
        ),
    ]
