# Generated by Django 5.2.1 on 2025-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0013_resident_building_resident_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='building',
            field=models.CharField(max_length=20, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='entrance',
            field=models.CharField(max_length=50, verbose_name='Вход'),
        ),
    ]
