# Generated by Django 5.2.1 on 2025-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_app', '0014_alter_resident_building_alter_resident_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='entrance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вход'),
        ),
    ]
