# Generated by Django 5.2.1 on 2025-07-26 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resident_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=15, unique=True, verbose_name='Номер карты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Карта лояльности',
                'verbose_name_plural': 'Карты лояльности',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Баллы')),
                ('price', models.FloatField(verbose_name='Сумма операции')),
                ('transaction_type', models.CharField(choices=[('начисление', 'начисление'), ('списание', 'списание')], max_length=10, verbose_name='Тип транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty_app.loyaltycard', verbose_name='Карта лояльности')),
                ('resident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resident_app.resident', verbose_name='Резидент')),
            ],
            options={
                'verbose_name': 'Транзакция баллов',
                'verbose_name_plural': 'Транзакции баллов',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала акции')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания акции')),
                ('photo', models.ImageField(upload_to='promotions/photos/', verbose_name='Фото акции')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрена ли акция')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на участие в акции')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент скидки')),
                ('promotional_code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='resident_app.resident', verbose_name='Резидент')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
