# Generated by Django 5.2.1 on 2025-07-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='discount_precent',
            new_name='discount_percent',
        ),
    ]
