# Generated by Django 5.2.1 on 2025-06-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0001_initial'),
        ('resident_app', '0002_category_remove_resident_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Баллы (-/+): списание или пополнение')),
                ('price', models.FloatField(verbose_name='Сумма с которой начислились баллы или списались')),
                ('transaction_type', models.CharField(choices=[('начисление', 'начисление'), ('списание', 'списание')], max_length=10, verbose_name='Тип транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty_app.loyaltycard')),
                ('resident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resident_app.resident')),
            ],
            options={
                'verbose_name': 'Транзакция баллов',
                'verbose_name_plural': 'Транзакции баллов',
            },
        ),
    ]
