# Generated by Django 5.2.1 on 2025-07-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_100_rubles', models.PositiveIntegerField(verbose_name='Кол-во баллов за 100 р.')),
                ('points_per_1_percent', models.PositiveIntegerField(verbose_name='Кол-во баллов за 1%')),
            ],
            options={
                'verbose_name': 'Транзакция баллов',
                'verbose_name_plural': 'Транзакции баллов',
            },
        ),
    ]
