# Generated by Django 5.2.1 on 2025-07-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0002_pointssystemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointssystemsettings',
            options={'verbose_name': 'Настройки программы лояльности', 'verbose_name_plural': 'Настройки программы лояльности'},
        ),
        migrations.CreateModel(
            name='UserPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by_users', to='loyalty_app.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Полученный промокод',
                'verbose_name_plural': 'Полученные промокоды',
                'unique_together': {('user', 'promotion')},
            },
        ),
    ]
