# Generated by Django 5.2.1 on 2025-06-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0002_pointstransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltycard',
            name='card_image',
        ),
    ]
