# Generated by Django 5.2.1 on 2025-07-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0003_alter_pointssystemsettings_options_userpromotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpromotion',
            options={'ordering': ['-redeemed_at'], 'verbose_name': 'Участие пользователя в акции', 'verbose_name_plural': 'Участия пользователей в акциях'},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='url',
        ),
    ]
