# Generated by Django 5.2.1 on 2025-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0003_remove_loyaltycard_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycard',
            name='card_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер карты'),
        ),
    ]
