# Generated by Django 5.2.1 on 2025-07-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0003_alter_loyaltycard_card_number'),
        ('resident_app', '0006_alter_resident_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала акции')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания акции')),
                ('photo', models.CharField(max_length=255, verbose_name='Фото акции')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрена ли акция')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на участие в акции')),
                ('discount_or_bonus', models.CharField(choices=[('скидка', 'Скидка'), ('бонус', 'Бонус')], max_length=10, verbose_name='Тип скидки или бонуса')),
                ('discount_or_bonus_value', models.FloatField(help_text='Введите значение скидки или бонуса, например 10% или 100 баллов', verbose_name='Значение скидки или бонуса')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='resident_app.resident', verbose_name='Резидент')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
