# Generated by Django 5.2.1 on 2025-07-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0004_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='photo',
            field=models.ImageField(upload_to='promotions/photos/', verbose_name='Фото акции'),
        ),
    ]
