# Generated by Django 5.2.1 on 2025-08-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0004_alter_userpromotion_options_remove_promotion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(max_length=700, verbose_name='Описание акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название акции'),
        ),
    ]
