# Generated by Django 5.2.1 on 2025-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0005_alter_promotion_description_alter_promotion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(max_length=750, verbose_name='Описание акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название акции'),
        ),
    ]
