# Generated by Django 5.2.1 on 2025-07-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0005_alter_promotion_photo'),
        ('resident_app', '0008_remove_resident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='resident_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resident_app.resident'),
        ),
    ]
