# Generated by Django 5.2.1 on 2025-07-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0006_alter_pointstransaction_resident_id'),
        ('resident_app', '0009_alter_resident_description_alter_resident_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty_app.loyaltycard', verbose_name='Карта лояльности'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='points',
            field=models.IntegerField(verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='price',
            field=models.FloatField(verbose_name='Сумма операции'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='resident_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resident_app.resident', verbose_name='Резидент'),
            preserve_default=False,
        ),
    ]
