# Generated by Django 5.2.1 on 2025-08-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0006_alter_promotion_description_alter_promotion_title'),
        ('resident_app', '0004_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='resident_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resident_app.resident', verbose_name='Резидент'),
        ),
    ]
