# Generated by Django 5.2.1 on 2025-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0007_alter_pointstransaction_resident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointssystemsettings',
            name='new_user_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы за регистрацию'),
        ),
        migrations.AlterField(
            model_name='pointssystemsettings',
            name='points_per_100_rubles',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во баллов за 100 р.'),
        ),
        migrations.AlterField(
            model_name='pointssystemsettings',
            name='points_per_1_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во баллов за 1%'),
        ),
    ]
