# Generated by Django 5.2.1 on 2025-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0008_pointssystemsettings_new_user_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointstransaction',
            options={'verbose_name': 'Транзакция бонусов', 'verbose_name_plural': 'Транзакции бонусов'},
        ),
        migrations.AlterField(
            model_name='pointssystemsettings',
            name='new_user_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусы за регистрацию'),
        ),
        migrations.AlterField(
            model_name='pointssystemsettings',
            name='points_per_100_rubles',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во бонусов за 100 р.'),
        ),
        migrations.AlterField(
            model_name='pointssystemsettings',
            name='points_per_1_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во бонусов за 1%'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='points',
            field=models.IntegerField(verbose_name='Бонусы'),
        ),
    ]
