# Generated by Django 5.2.1 on 2025-10-08 14:53

import dzavod.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0009_alter_pointstransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='photo',
            field=models.ImageField(upload_to='promotions/photos/', validators=[dzavod.validators.validate_image], verbose_name='Фото акции'),
        ),
    ]
