# Generated by Django 5.2.1 on 2025-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, unique=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование типа'),
        ),
    ]
